apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-otel-config
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318" # Specifies the OpenTelemetry Collector endpoint
  CORECLR_ENABLE_PROFILING: "1"
  CORECLR_PROFILER: '{918728DD-259F-4A6A-AC2B-B85E1B658318}'
  CORECLR_PROFILER_PATH: "/otel-dotnet-auto/linux-x64/OpenTelemetry.AutoInstrumentation.Native.so"
  DOTNET_ADDITIONAL_DEPS: "/otel-dotnet-auto/AdditionalDeps"
  DOTNET_SHARED_STORE: "/otel-dotnet-auto/store"
  DOTNET_STARTUP_HOOKS: "/otel-dotnet-auto/net/OpenTelemetry.AutoInstrumentation.StartupHook.dll"
  OTEL_DOTNET_AUTO_HOME: "/otel-dotnet-auto"
  OTEL_METRIC_EXPORT_INTERVAL: "5000"
