apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-backend
  labels:
    app: kotlin-backend
    app.kubernetes.io/name: kotlin-backend
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    app.kubernetes.io/component: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotlin-backend
  template:
    metadata:
      labels:
        app: kotlin-backend
    spec:
      containers:
        - image: europe-west4-docker.pkg.dev/operationalexcellence-439615/operational-excellence/kotlin-backend:0.0.1-SNAPSHOT
          name: kotlin-backend
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
            requests:
              cpu: "0.25"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            failureThreshold: 5
          ports:
            - name: http
              containerPort: 9001
          env:
            # Some custom configuration for the Docker image generated by the Spring Boot Gradle plugin.
            - name: BPL_JVM_THREAD_COUNT
              value: "100" # Used in memory calculation only. Defaults to 250, but that's very generous.
            - name: JAVA_TOOL_OPTIONS
              value: "-Xss512k" # Set thread stack size to 512k. Defaults to 1M, but in a typical Spring Boot application, less is needed.
            - name: ENV_PERSISTENCE_URL
              value: "http://persistence-service.default.svc.cluster.local:1337"
          envFrom:
            - configMapRef:
                name: java-otel-config
