apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-fe
  labels:
    app: otel-collector-fe
    app.kubernetes.io/name: otel-collector-fe
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    app.kubernetes.io/component: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector-fe
  template:
    metadata:
      labels:
        app: otel-collector-fe
    spec:
      containers:
        - image: europe-west4-docker.pkg.dev/operationalexcellence-439615/operational-excellence/otel-collector-fe:0.0.1-SNAPSHOT
          name: otel-collector-fe
          imagePullPolicy: Always
          resources:
            limits:
              memory: "32Mi"
            requests:
              cpu: "0.1"
              memory: "32Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            failureThreshold: 5
          ports:
            - name: http
              containerPort: 80
