apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel-collector-fe
  name: otel-collector-fe
spec:
  type: NodePort
  selector:
    app: otel-collector-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
